# Generated by Django 4.2.5 on 2023-09-12 06:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=200)),
                ('lastname', models.TextField(max_length=200)),
                ('emailid', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=25)),
                ('phone_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
            ],
        ),
    ]
