# Generated by Django 4.2.5 on 2023-09-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
