# Generated by Django 4.2.5 on 2023-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
