# Generated by Django 4.2.5 on 2023-09-16 05:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN'),
        ),
    ]
